a = float(input())
b = float(input())
result = a + b
print(a, '+', b, '=', result)
result = a-b
print(a, '-', b, '=', result)
result = a*b
print(a, '*', b, '=', result)
result = a/b
print(a, '/', b, '=', result)